version: '3.8'
services:
  web:
    image: ghcr.io/supercakecrumb/private-eurovision-voting-website:0.1.4
    ports:
      - "5024:5000"
    volumes:
      - ./data:/data  # For any file storage needs
    depends_on:
      - db
    environment:
      # Database connection
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/eurovision
      # Set to 1 to automatically initialize the database with Eurovision data when the app starts
      - AUTO_INIT_DB=1
      # Set to 1 to use real Eurovision 2023 data instead of dummy data
      - USE_REAL_EUROVISION_DATA=0
      # Optional: Set a custom secret key for session security
      - SECRET_KEY=${SECRET_KEY:-default_dev_key_change_in_production}
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=eurovision
    ports:
      - "5432:5432"  # Expose PostgreSQL port (optional, for external connections)
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:  # Persistent volume for database data
